import os
import click
import pandas as pd
import numpy as np
from scipy.stats import expon
from skbio.stats.composition import perturb, closure
from pls_balances.src.generators import (compositional_effect_size_generator,
                                         compositional_variable_features_generator)
from pls_balances.src.sim import multinomial_sample, compositional_noise

from biom import Table, load_table
from biom.util import biom_open


def deposit(table, groups, truth,
            output_table, output_groups, output_truth):
    t = Table(table.T.values, table.columns.values, table.index.values)
    with biom_open(output_table, 'w') as f:
        t.to_hdf5(f, generated_by='moi')
    groups.to_csv(output_groups, sep='\t')
    truth.to_csv(output_truth)


@click.group()
def generate():
    pass


@generate.command()
@click.option('--table-file',
              help='Input biom table of abundances.')
@click.option('--metadata-file',
              help='Input metadata file that was autogenerated.')
@click.option('--sigma', default=0.1,
              help='Variance of compositional noise')
@click.option('--lam', default=0.2,
              help='Exponential decay parameter of contaminants')
@click.option('--n-contaminants', default=30,
              help='Number of contaminant species')
@click.option('--output-file',
              help='output file of modified biom table.')
def noisify(table_file, metadata_file,
            sigma, lam, n_contaminants, output_file):

    metadata = pd.read_table(metadata_file, index_col=0)
    table = load_table(table_file)
    table = pd.DataFrame(np.array(table.matrix_data.todense()).T,
                         index=table.ids(axis='sample'),
                         columns=table.ids(axis='observation'))
    cov = np.eye(table.shape[1] - 1)
    m_noise = compositional_noise(cov, nsamp=table.shape[0])
    table_ = table.values
    table_ = np.vstack([
        perturb(table_[i, :], m_noise[i, :])
        for i in range(table_.shape[0])])

    x = np.linspace(0, 1, n_contaminants)
    contaminant_urn = closure(expon.pdf(x, scale=lam))

    contaminant_urns = np.repeat(np.expand_dims(contaminant_urn, axis=0),
                                 table_.shape[0], axis=0)
    table_ = np.hstack((table_, contaminant_urns))
    table_ = closure(table_)

    # note that this assumes that the column is named `library_size
    table_ = pd.DataFrame(
        multinomial_sample(table_, depths=metadata['library_size']))
    table_.index = table.index
    new_ids = ['X%d' % i for i in range(len(table.columns), len(table_.columns))]
    table_.columns = list(table.columns) + new_ids
    t = Table(table_.T.values, table_.columns.values, table_.index.values)
    with biom_open(output_file, 'w') as f:
        t.to_hdf5(f, generated_by='moi')


@generate.command()
@click.option('--max-alpha', default=2,
              help='Maximum effect size.')
@click.option('--reps', default=30,
              help='Number of samples in each group.')
@click.option('--intervals', default=30,
              help='Number of effect size benchmarks to test.')
@click.option('--n-species', default=100,
              help='Number of species')
@click.option('--output-dir',
              help='output directory')
def compositional_effect_size(max_alpha, reps, intervals,
                              n_species, output_dir):

    gen = compositional_effect_size_generator(
        max_alpha, reps, intervals, n_species
    )
    os.mkdir(output_dir)
    for i, g in enumerate(gen):
        table, groups, truth = g
        output_table = "%s/table.%d.biom" % (output_dir, i)
        output_groups = "%s/metadata.%d.txt" % (output_dir, i)
        output_truth = "%s/truth.%d.csv" % (output_dir, i)
        deposit(table, groups, truth,
                output_table, output_groups, output_truth)


@generate.command()
@click.option('--max-changing', default=2,
              help='Maximum number of changing species.')
@click.option('--fold-change', default=2,
              help='Fold change of changing species.')
@click.option('--reps', default=30,
              help='Number of samples in each group.')
@click.option('--intervals', default=30,
              help='Number of effect size benchmarks to test.')
@click.option('--n-species', default=100,
              help='Number of species')
@click.option('--output-dir',
              help='output directory')
def compositional_variable_features(max_changing, fold_change, reps,
                                    intervals, n_species,
                                    output_dir):

    gen = compositional_effect_size_generator(
        max_alpha, reps, intervals, n_species
    )
    os.mkdir(output_dir)
    for i, g in enumerate(gen):
        table, groups, truth = g
        output_table = "%s/table.%d.biom" % (output_dir, i)
        output_groups = "%s/metadata.%d.txt" % (output_dir, i)
        output_truth = "%s/truth.%d.csv" % (output_dir, i)
        deposit(table, groups, truth,
                output_table, output_groups, output_truth)


if __name__ == "__main__":
    generate()
